---
- name: Docker Swarm Manager Setup
  hosts: manager_node
  become: yes # root 권한으로 실행
  tasks:
    - name: Install Docker and Docker Compose
      ansible.builtin.apk:
        name:
          - docker
          - docker-compose
        state: present

    - name: Ensure Docker service is running and enabled on boot
      ansible.builtin.service:
        name: docker
        state: started
        enabled: yes

    - name: Add 'pi' user to 'docker' group
      ansible.builtin.user:
        name: pi
        groups: docker
        append: yes

    - name: Initialize Docker Swarm
      community.docker.docker_swarm:
        state: present
        advertise_addr: "{{ ansible_host }}"

    - name: Create /etc/docker/daemon.json for live-restore
      ansible.builtin.copy:
        content: |
          {
            "live-restore": true
          }
        dest: /etc/docker/daemon.json
        mode: "0644"
