---
- name: Notify about default admin creation
  ansible.builtin.debug:
    msg: "⚠️ 'cluster_managers' list is empty. Creating default cluster manager 'cm'."
  when: cluster_managers | default([]) | length == 0

- name: Determine the list of managers to create
  ansible.builtin.set_fact:
    managers: "{{ cluster_managers if (cluster_managers is defined and cluster_managers | length > 0) else ['cm'] }}"

- name: Ensure 'cluster_managers' group exists
  ansible.builtin.group:
    name: cluster_managers
    state: present

- name: Ensure all manager users exist
  ansible.builtin.user:
    name: "{{ item }}"
    state: present
    shell: /bin/ash
  loop: "{{ managers }}"
  register: user_creation_results

- name: Set password for new users only
  vars:
    current_user: "{{ item.item }}"
  block:
    - name: "Prompt for password for new user: {{ item.item }}"
      ansible.builtin.pause:
        prompt: "Enter password for new user '{{ current_user }}'"
        echo: no
      register: password_prompt

    - name: Set user password
      ansible.builtin.user:
        name: "{{ current_user }}"
        password: "{{ password_prompt.user_input | password_hash('sha512') }}"
  loop: "{{ user_creation_results.results }}"
  when: item.changed

- name: Add manager users to the 'docker' group
  ansible.builtin.user:
    name: "{{ item }}"
    groups: docker
    append: yes
  loop: "{{ managers }}"

- name: Ensure only specified users are in 'cluster_managers' group
  ansible.builtin.group:
    name: cluster_managers
    state: present
    members: "{{ managers }}"

- name: Set permissions for the cluster_setup directory
  ansible.builtin.file:
    path: /cluster_setup
    state: directory
    owner: "{{ managers | first }}"
    group: cluster_managers
    mode: '0770'
    recurse: yes